# Generated by Django 3.2 on 2022-02-05 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('favorito_id', models.AutoField(primary_key=True, serialize=False)),
                ('favorito_titulo', models.CharField(max_length=100, verbose_name='titulo')),
                ('favorito_url', models.CharField(max_length=200, verbose_name='url')),
                ('favorito_fecha', models.DateTimeField(null=True, verbose_name='Fecha de registro')),
            ],
        ),
    ]
